name: Django App Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Build Docker image
        run: |
          docker build -t your-django-app .
          docker tag your-django-app:latest 810638962855.dkr.ecr.eu-central-1.amazonaws.com/demo/your-django-app:latest

      - name: Push Docker image to ECR
        run: |
          docker push 810638962855.dkr.ecr.eu-central-1.amazonaws.com/demo/your-django-app:latest

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-197-57-243.eu-central-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop your-django-app || true
            docker rm your-django-app || true
            docker pull 810638962855.dkr.ecr.eu-central-1.amazonaws.com/demo/your-django-app:latest
            docker run -d -p 8000:8000 --name your-django-app 810638962855.dkr.ecr.eu-central-1.amazonaws.com/demo/your-django-app:latest
